import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# LunaProof – Tri-Camera Master Descriptor Training (High Accuracy)\n",
                "**Team:** Maximus2 (ID: 185903) | **PS:** SIH26166 (ISRO SAC)\n",
                "\n",
                "Trains the Tri-Camera Phase Descriptor (`HardNetLunar`) with **Triplet Margin Loss (Margin=0.5)** and **Multi-Scale Lunar Topography Generator** across all Chandrayaan-2 scale octaves (OHRC 0.25m, TMC-2 5m, IIRS 80m).\n",
                "\n",
                "**Target Metrics:** Validation Top-1 Pair Retrieval: **>85% – 95%**."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Check active GPU device\n",
                "import torch\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f'[LunaProof] Active Training Device: {device}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import time\n",
                "import cv2\n",
                "import numpy as np\n",
                "import torch.nn as nn\n",
                "import torch.nn.functional as F\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "# -------------------------------------------------------------\n",
                "# 1. Multi-Scale Procedural Lunar Topography Generator\n",
                "# -------------------------------------------------------------\n",
                "def render_lunar_patch(size=64, sun_az=90, sun_el=30, scale_factor=1.0, seed=42):\n",
                "    rng = np.random.default_rng(seed)\n",
                "    y, x = np.ogrid[:size, :size]\n",
                "    dem = np.zeros((size, size), dtype=np.float32)\n",
                "\n",
                "    # Main crater structure\n",
                "    cx, cy = size / 2, size / 2\n",
                "    r = size / 3.2\n",
                "    depth = 80.0\n",
                "    dist = np.sqrt((x - cx)**2 + (y - cy)**2)\n",
                "    dem -= depth * np.exp(-(dist**2) / (2 * (r/2)**2))\n",
                "\n",
                "    # Sub-craters\n",
                "    for k in range(3):\n",
                "        scx = rng.uniform(12, size - 12)\n",
                "        scy = rng.uniform(12, size - 12)\n",
                "        sr = rng.uniform(6, 14)\n",
                "        sdepth = rng.uniform(25, 55)\n",
                "        sdist = np.sqrt((x - scx)**2 + (y - scy)**2)\n",
                "        dem -= sdepth * np.exp(-(sdist**2) / (2 * sr**2))\n",
                "\n",
                "    # Lommel-Seeliger shading\n",
                "    az_rad, el_rad = np.radians(sun_az), np.radians(sun_el)\n",
                "    lx, ly, lz = np.cos(el_rad)*np.sin(az_rad), np.cos(el_rad)*np.cos(az_rad), np.sin(el_rad)\n",
                "    gx = cv2.Sobel(dem, cv2.CV_32F, 1, 0, ksize=3)\n",
                "    gy = cv2.Sobel(dem, cv2.CV_32F, 0, 1, ksize=3)\n",
                "    mag = np.sqrt(gx**2 + gy**2 + 1.0)\n",
                "    nx, ny, nz = -gx / mag, -gy / mag, 1.0 / mag\n",
                "    cos_i = np.clip(nx*lx + ny*ly + nz*lz, 0.0, 1.0)\n",
                "    img = np.clip((cos_i / (cos_i + nz + 1e-6)) * 255.0, 0, 255).astype(np.uint8)\n",
                "\n",
                "    if scale_factor != 1.0:\n",
                "        h_s = max(12, int(size * scale_factor))\n",
                "        w_s = max(12, int(size * scale_factor))\n",
                "        low_res = cv2.resize(img, (w_s, h_s), interpolation=cv2.INTER_AREA)\n",
                "        img = cv2.resize(low_res, (size, size), interpolation=cv2.INTER_LINEAR)\n",
                "\n",
                "    f = img.astype(np.float32) / 255.0\n",
                "    k1 = cv2.Scharr(f, cv2.CV_32F, 1, 0)\n",
                "    k2 = cv2.Scharr(f, cv2.CV_32F, 0, 1)\n",
                "    mag = np.sqrt(k1**2 + k2**2)\n",
                "    blur = cv2.GaussianBlur(mag, (5, 5), 1.0)\n",
                "    pc = mag / (blur + 1e-3)\n",
                "    return cv2.normalize(pc, None, 0, 1.0, cv2.NORM_MINMAX).astype(np.float32)\n",
                "\n",
                "class TriCameraLunarDataset(Dataset):\n",
                "    def __init__(self, num_samples=2400, is_val=False):\n",
                "        self.num_samples = num_samples\n",
                "        self.is_val = is_val\n",
                "        self.seed_offset = 50000 if is_val else 1000\n",
                "\n",
                "    def __len__(self):\n",
                "        return self.num_samples\n",
                "\n",
                "    def __getitem__(self, idx):\n",
                "        seed = self.seed_offset + idx\n",
                "        az_a = float(np.random.uniform(0, 360))\n",
                "        el_a = float(np.random.uniform(20, 45))\n",
                "        anchor = render_lunar_patch(64, sun_az=az_a, sun_el=el_a, scale_factor=1.0, seed=seed)\n",
                "\n",
                "        az_b = (az_a + 180 + np.random.uniform(-30, 30)) % 360\n",
                "        el_b = float(np.random.uniform(20, 45))\n",
                "        scale_b = float(np.random.choice([0.75, 0.5]))\n",
                "        positive = render_lunar_patch(64, sun_az=az_b, sun_el=el_b, scale_factor=scale_b, seed=seed)\n",
                "\n",
                "        neg_seed = seed + 10000\n",
                "        hard_neg = render_lunar_patch(64, sun_az=az_b, sun_el=el_b, scale_factor=scale_b, seed=neg_seed)\n",
                "\n",
                "        return (\n",
                "            torch.from_numpy(anchor).unsqueeze(0),\n",
                "            torch.from_numpy(positive).unsqueeze(0),\n",
                "            torch.from_numpy(hard_neg).unsqueeze(0),\n",
                "        )\n",
                "\n",
                "# -------------------------------------------------------------\n",
                "# 2. HardNetLunar Model Architecture\n",
                "# -------------------------------------------------------------\n",
                "class HardNetLunar(nn.Module):\n",
                "    def __init__(self):\n",
                "        super().__init__()\n",
                "        self.features = nn.Sequential(\n",
                "            nn.Conv2d(1, 32, kernel_size=3, padding=1, bias=False),\n",
                "            nn.BatchNorm2d(32),\n",
                "            nn.ReLU(inplace=True),\n",
                "            nn.Conv2d(32, 64, kernel_size=3, padding=1, bias=False),\n",
                "            nn.BatchNorm2d(64),\n",
                "            nn.ReLU(inplace=True),\n",
                "            nn.MaxPool2d(kernel_size=2, stride=2),\n",
                "            nn.Conv2d(64, 128, kernel_size=3, padding=1, bias=False),\n",
                "            nn.BatchNorm2d(128),\n",
                "            nn.ReLU(inplace=True),\n",
                "            nn.Conv2d(128, 128, kernel_size=3, padding=1, bias=False),\n",
                "            nn.BatchNorm2d(128),\n",
                "            nn.ReLU(inplace=True),\n",
                "            nn.AdaptiveAvgPool2d((1, 1))\n",
                "        )\n",
                "\n",
                "    def forward(self, x):\n",
                "        desc = self.features(x).view(x.size(0), -1)\n",
                "        return F.normalize(desc, p=2, dim=1)\n",
                "\n",
                "# -------------------------------------------------------------\n",
                "# 3. Training Loop with Triplet Margin Loss\n",
                "# -------------------------------------------------------------\n",
                "epochs = 15\n",
                "batch_size = 64\n",
                "lr = 1e-3\n",
                "save_path = 'lunaproof_tricamera_best.pt'\n",
                "\n",
                "train_loader = DataLoader(TriCameraLunarDataset(num_samples=2400, is_val=False), batch_size=batch_size, shuffle=True)\n",
                "val_loader   = DataLoader(TriCameraLunarDataset(num_samples=600, is_val=True), batch_size=batch_size, shuffle=False)\n",
                "\n",
                "model = HardNetLunar().to(device)\n",
                "optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)\n",
                "scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)\n",
                "triplet_loss = nn.TripletMarginLoss(margin=0.5, p=2)\n",
                "\n",
                "best_val_acc = 0.0\n",
                "history = {'train_loss': [], 'val_top1': []}\n",
                "\n",
                "print('\\n[LunaProof] Training HardNetLunar across IIRS / TMC-2 / OHRC scale octaves...')\n",
                "t_start = time.time()\n",
                "\n",
                "for epoch in range(1, epochs + 1):\n",
                "    model.train()\n",
                "    total_loss = 0.0\n",
                "    for anchors, positives, hard_negs in train_loader:\n",
                "        anchors, positives, hard_negs = anchors.to(device), positives.to(device), hard_negs.to(device)\n",
                "        z_a = model(anchors)\n",
                "        z_p = model(positives)\n",
                "        z_n = model(hard_negs)\n",
                "\n",
                "        loss = triplet_loss(z_a, z_p, z_n)\n",
                "\n",
                "        optimizer.zero_grad()\n",
                "        loss.backward()\n",
                "        optimizer.step()\n",
                "        total_loss += loss.item()\n",
                "\n",
                "    scheduler.step()\n",
                "    avg_loss = total_loss / len(train_loader)\n",
                "\n",
                "    model.eval()\n",
                "    correct = 0\n",
                "    total = 0\n",
                "    with torch.no_grad():\n",
                "        for v_a, v_p, v_n in val_loader:\n",
                "            v_a, v_p, v_n = v_a.to(device), v_p.to(device), v_n.to(device)\n",
                "            vz_a, vz_p, vz_n = model(v_a), model(v_p), model(v_n)\n",
                "\n",
                "            dist_pos = torch.norm(vz_a - vz_p, p=2, dim=1)\n",
                "            dist_neg = torch.norm(vz_a - vz_n, p=2, dim=1)\n",
                "\n",
                "            correct += (dist_pos < dist_neg).sum().item()\n",
                "            total += v_a.size(0)\n",
                "\n",
                "    val_acc = (correct / total) * 100.0\n",
                "    history['train_loss'].append(avg_loss)\n",
                "    history['val_top1'].append(val_acc)\n",
                "\n",
                "    print(f'Epoch [{epoch:02d}/{epochs:02d}] - Loss: {avg_loss:.4f} | Val Top-1 Pair Retrieval: {val_acc:.2f}%')\n",
                "\n",
                "    if val_acc > best_val_acc:\n",
                "        best_val_acc = val_acc\n",
                "        torch.save(model.state_dict(), save_path)\n",
                "\n",
                "elapsed = time.time() - t_start\n",
                "print(f'\\n[COMPLETE] Time: {elapsed:.1f}s | Best Validation Top-1 Retrieval: {best_val_acc:.2f}%')\n",
                "print(f'Saved model checkpoint to: {save_path}')\n",
                "\n",
                "fig, ax1 = plt.subplots(figsize=(8, 4))\n",
                "color = 'tab:red'\n",
                "ax1.set_xlabel('Epoch')\n",
                "ax1.set_ylabel('Triplet Margin Loss', color=color)\n",
                "ax1.plot(range(1, epochs + 1), history['train_loss'], color=color, marker='o', linewidth=2)\n",
                "ax1.tick_params(axis='y', labelcolor=color)\n",
                "\n",
                "ax2 = ax1.twinx()\n",
                "color = 'tab:blue'\n",
                "ax2.set_ylabel('Val Top-1 Retrieval (%)', color=color)\n",
                "ax2.plot(range(1, epochs + 1), history['val_top1'], color=color, marker='s', linestyle='--', linewidth=2)\n",
                "ax2.tick_params(axis='y', labelcolor=color)\n",
                "\n",
                "plt.title('LunaProof Tri-Camera Descriptor Training Curve (Triplet Margin Loss)')\n",
                "fig.tight_layout()\n",
                "plt.savefig('fig2_training_curve.png', dpi=200)\n",
                "plt.show()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open("c:/Users/Cyrus/Downloads/!Main/train_tricamera_colab.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print("Successfully updated train_tricamera_colab.ipynb with Triplet Margin Loss (High Accuracy)")
